# my_config.yaml

# Paths
data_path: data/raw/
data_path_1: data/raw/daily_weather.parquet
data_path_2: data/raw/london_weather.csv
results_path: 'results/res1.json'

# Log Parameters
logging:
  level: INFO                         # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

##############################################################
