# my_config.yaml

##########################################################################################

# TORCH PROCESSING
window_size: 365
batch_size: 16

##########################################################################################

# LOGGING
logging:
  file_level: DEBUG
  console_level: DEBUG

##########################################################################################

# VARS
input_variable: "avg_temp_c"
variables: ["avg_sea_level_pres_hpa", "avg_temp_c", "precipitation_mm"]
windows: [7, 30] # Plotting windows

##########################################################################################

# PATHS
data_paths:
  - data/raw/daily_weather.parquet
  - data/raw/london_weather.csv
  - data/raw/countries.csv
  - data/raw/cities.csv

processed_data: "data/processed/processed_data.xlsx"
processed_data_comp: "data/processed/processed_data.parq"

results_path: "results/model_res.json"
summary_path: "results/model_summary.txt"
fig_path: reports/figures/

##########################################################################################

# PROCESSING
processing:
  to_impute:
    - avg_temp_c
    - precipitation_mm
    - avg_sea_level_pres_hpa
    - min_temp_c
    - max_temp_c
    - snow_depth_mm
  impute_with:
    - mean_temp
    - precipitation
    - pressure
    - min_temp
    - max_temp
    - snow_depth
  impute_zero_cols:
    - avg_wind_speed_kmh
    - snow_depth_mm
  impute_mean_cols:
    - avg_sea_level_pres_hpa
    - min_temp_c
    - max_temp_c
  impute_bfill_cols:
    - precipitation_mm
  keep_cols:
    - date
    - year
    - month
    - day
    - season_num
    - day_of_year
    - avg_temp_c
    - min_temp_c
    - max_temp_c
    - precipitation_mm
    - snow_depth_mm
    - avg_wind_speed_kmh
    - avg_sea_level_pres_kpa

##########################################################################################
