
image: python:3.12

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - test
  - lint
  - deploy

test:
  stage: test
  script:
    - pytest  # Add your test command/script here
    - echo "Test stage completed!"

lint:
  stage: lint
  script:
    - pip install flake8 black
    - flake8 .  # Linting with Flake8
    - black . --check  # Code formatting check with Black

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy your application here"
#   only:
#     - main  # or replace 'main' with your default branch
